name: idealmart_customer
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  get: ^4.6.6
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.2.0
  fluentui_system_icons: ^1.1.248
  fluentui_icons: ^1.0.0
  iconsax: ^0.0.8

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
